### ISSUE TITLE
Unable to run eval_batch.py

### ISSUE THREAD

**Issue by ashokrajab** [bailuding/rails#1]
I have install all the dependencies as stated in the readme.md

```
pip3 install transformers faiss-gpu accelerate k-means-constrained pandas gin-config tensorboard
pip3 install torch torchvision torchaudio
pip3 install fbgemm-gpu --index-url https://download.pytorch.org/whl/cu121/
pip install -r requirements.txt
```

and when I try to run eval_batch.py, I get the below error.

```
(rails_env) $ python3 eval_batch.py
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLBruteForceTopK  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLNaiveTopK5  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLNaiveFaissTopK5  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346

INFO:root:Rank 0: loading gin config from configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin
INFO:root:Enabling eval in bf16 to speed up.
INFO:root:Evaluating model on rank 0.
Initialize _item_emb.weight as truncated normal: torch.Size([3953, 50]) params
Initialize _ndp_module._gating_fn._query_only_partial_module.0.weight as xavier normal: torch.Size([128, 50]) params
Failed to initialize _ndp_module._gating_fn._query_only_partial_module.0.bias: torch.Size([128]) params
Initialize _ndp_module._gating_fn._query_only_partial_module.2.weight as xavier normal: torch.Size([32, 128]) params
Initialize _ndp_module._gating_fn._item_only_partial_module.1.weight as xavier normal: torch.Size([128, 50]) params
Failed to initialize _ndp_module._gating_fn._item_only_partial_module.1.bias: torch.Size([128]) params
Initialize _ndp_module._gating_fn._item_only_partial_module.3.weight as xavier normal: torch.Size([32, 128]) params
Initialize _ndp_module._gating_fn._qi_partial_module.1.weight as xavier normal: torch.Size([128, 32]) params
Failed to initialize _ndp_module._gating_fn._qi_partial_module.1.bias: torch.Size([128]) params
Initialize _ndp_module._gating_fn._qi_partial_module.3.weight as xavier normal: torch.Size([32, 128]) params
Failed to initialize _ndp_module._gating_fn._qi_partial_module.3.bias: torch.Size([32]) params
Initialize _ndp_module._query_embeddings_fn._query_emb_proj_module.1._w as xavier normal: torch.Size([50, 1024]) params
Initialize _ndp_module._query_embeddings_fn._query_emb_proj_module.1._b as xavier normal: torch.Size([1, 1024]) params
Initialize _ndp_module._query_embeddings_fn._query_emb_proj_module.2.weight as xavier normal: torch.Size([448, 512]) params
Failed to initialize _ndp_module._query_embeddings_fn._query_emb_proj_module.2.bias: torch.Size([448]) params
Initialize _ndp_module._query_embeddings_fn._uid_embeddings_0.weight as xavier normal: torch.Size([6041, 64]) params
Initialize _ndp_module._item_proj_module.1.weight as xavier normal: torch.Size([256, 50]) params
Failed to initialize _ndp_module._item_proj_module.1.bias: torch.Size([256]) params
Skipping init for _embedding_module._item_emb.weight
Initialize _input_features_preproc._pos_emb.weight as xavier normal: torch.Size([211, 50]) params
Skipping init for _hstu._attention_layers.0._uvqk
Skipping init for _hstu._attention_layers.0._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.0._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.0._o.weight
Skipping init for _hstu._attention_layers.0._o.bias
Skipping init for _hstu._attention_layers.1._uvqk
Skipping init for _hstu._attention_layers.1._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.1._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.1._o.weight
Skipping init for _hstu._attention_layers.1._o.bias
Skipping init for _hstu._attention_layers.2._uvqk
Skipping init for _hstu._attention_layers.2._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.2._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.2._o.weight
Skipping init for _hstu._attention_layers.2._o.bias
Skipping init for _hstu._attention_layers.3._uvqk
Skipping init for _hstu._attention_layers.3._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.3._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.3._o.weight
Skipping init for _hstu._attention_layers.3._o.bias
Skipping init for _hstu._attention_layers.4._uvqk
Skipping init for _hstu._attention_layers.4._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.4._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.4._o.weight
Skipping init for _hstu._attention_layers.4._o.bias
Skipping init for _hstu._attention_layers.5._uvqk
Skipping init for _hstu._attention_layers.5._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.5._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.5._o.weight
Skipping init for _hstu._attention_layers.5._o.bias
Skipping init for _hstu._attention_layers.6._uvqk
Skipping init for _hstu._attention_layers.6._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.6._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.6._o.weight
Skipping init for _hstu._attention_layers.6._o.bias
Skipping init for _hstu._attention_layers.7._uvqk
Skipping init for _hstu._attention_layers.7._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.7._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.7._o.weight
Skipping init for _hstu._attention_layers.7._o.bias
INFO:root:Restored model and optimizer state from epoch 75's ckpt: ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75. Setting cur_epoch to 75
INFO:faiss.loader:Loading faiss with AVX2 support.
INFO:faiss.loader:Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
INFO:faiss.loader:Loading faiss.
INFO:faiss.loader:Successfully loaded faiss.
' b'/data/ashok-4983/rails/modeling/initialization.py:31: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  torch.nn.init.xavier_uniform(m.weight)
Traceback (most recent call last):
  File "/data/ashok-4983/rails/eval_from_checkpoint.py", line 394, in <module>
    app.run(main)
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/data/ashok-4983/rails/eval_from_checkpoint.py", line 387, in main
    mp.spawn(mp_train_fn,
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/data/ashok-4983/rails/eval_from_checkpoint.py", line 373, in mp_train_fn
    train_fn(
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/data/ashok-4983/rails/eval_from_checkpoint.py", line 292, in train_fn
    eval_state = get_eval_state(
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/ashok-4983/rails/data/eval.py", line 188, in get_eval_state
    top_k_module=top_k_module_fn(eval_negative_embeddings, eval_negatives_ids)
  File "/data/ashok-4983/rails/eval_from_checkpoint.py", line 296, in <lambda>
    top_k_module_fn=lambda item_embeddings, item_ids: get_top_k_module(
  File "/data/ashok-4983/rails/indexing/utils_rails.py", line 51, in get_top_k_module
    top_k_module = MoLNaiveTopK(
  File "/data/ashok-4983/rails/indexing/mol_top_k.py", line 152, in __init__
    index.train(mol_item_embeddings_np)  # train with the dataset vectors
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/faiss/__init__.py", line 280, in replacement_train
    self.train_c(n, swig_ptr(x))
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/faiss/swigfaiss.py", line 5104, in train
    return _swigfaiss.IndexIVF_train(self, n, x)
TypeError: in method 'IndexIVF_train', argument 3 of type 'float const *'
  In call to configurable 'train_fn' (<function train_fn at 0x7f366c303760>)

Traceback (most recent call last):
  File "/eval_batch.py", line 90, in <module>
    result = eval(dataset=dataset, batch_size=batch_size)
  File "/eval_batch.py", line 82, in eval
    eval_data.append(algorithm + "," + result[1])
TypeError: 'NoneType' object is not subscriptable
```

Any idea on how to resolve this?

**Comment by jiaqizhai** [comment]
Hi - this seems like a problem with your faiss installation, as NVIDIA GPUs should not support AVX instructions. You can try reinstalling faiss (pip uninstall faiss-gpu  and reinstall the 1.8.0 version specified in requirements.txt). https://github.com/facebookresearch/faiss/blob/main/INSTALL.md may also help.

**Comment by ashokrajab** [comment]
Hi @jiaqizhai ,

Thank you for the quick response. As you have suggested reinstalling faiss with a different version resolved the above issue but gave raise to another issue:

```
$ python eval_batch.py 
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLBruteForceTopK  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLNaiveTopK5  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLNaiveFaissTopK5  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLNaiveTopK10  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLNaiveTopK50  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLNaiveTopK100  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLAvgTopK200  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLAvgTopK500  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLAvgTopK1000  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLAvgTopK2000  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eval_batch_size=32 --limit_eval_to_first_n=0 --gin_config_file=configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin --top_k_method=MoLAvgTopK4000  --inference_from_ckpt=ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
1 b"INFO:root:Rank 0: loading gin config from configs/ml-1m/hstu-mol-sampled-softmax-n128-8x4x64-rails-final.gin
INFO:root:Enabling eval in bf16 to speed up.
INFO:root:Evaluating model on rank 0.
Initialize _item_emb.weight as truncated normal: torch.Size([3953, 50]) params
Initialize _ndp_module._gating_fn._query_only_partial_module.0.weight as xavier normal: torch.Size([128, 50]) params
Failed to initialize _ndp_module._gating_fn._query_only_partial_module.0.bias: torch.Size([128]) params
Initialize _ndp_module._gating_fn._query_only_partial_module.2.weight as xavier normal: torch.Size([32, 128]) params
Initialize _ndp_module._gating_fn._item_only_partial_module.1.weight as xavier normal: torch.Size([128, 50]) params
Failed to initialize _ndp_module._gating_fn._item_only_partial_module.1.bias: torch.Size([128]) params
Initialize _ndp_module._gating_fn._item_only_partial_module.3.weight as xavier normal: torch.Size([32, 128]) params
Initialize _ndp_module._gating_fn._qi_partial_module.1.weight as xavier normal: torch.Size([128, 32]) params
Failed to initialize _ndp_module._gating_fn._qi_partial_module.1.bias: torch.Size([128]) params
Initialize _ndp_module._gating_fn._qi_partial_module.3.weight as xavier normal: torch.Size([32, 128]) params
Failed to initialize _ndp_module._gating_fn._qi_partial_module.3.bias: torch.Size([32]) params
Initialize _ndp_module._query_embeddings_fn._query_emb_proj_module.1._w as xavier normal: torch.Size([50, 1024]) params
Initialize _ndp_module._query_embeddings_fn._query_emb_proj_module.1._b as xavier normal: torch.Size([1, 1024]) params
Initialize _ndp_module._query_embeddings_fn._query_emb_proj_module.2.weight as xavier normal: torch.Size([448, 512]) params
Failed to initialize _ndp_module._query_embeddings_fn._query_emb_proj_module.2.bias: torch.Size([448]) params
Initialize _ndp_module._query_embeddings_fn._uid_embeddings_0.weight as xavier normal: torch.Size([6041, 64]) params
Initialize _ndp_module._item_proj_module.1.weight as xavier normal: torch.Size([256, 50]) params
Failed to initialize _ndp_module._item_proj_module.1.bias: torch.Size([256]) params
Skipping init for _embedding_module._item_emb.weight
Initialize _input_features_preproc._pos_emb.weight as xavier normal: torch.Size([211, 50]) params
Skipping init for _hstu._attention_layers.0._uvqk
Skipping init for _hstu._attention_layers.0._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.0._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.0._o.weight
Skipping init for _hstu._attention_layers.0._o.bias
Skipping init for _hstu._attention_layers.1._uvqk
Skipping init for _hstu._attention_layers.1._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.1._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.1._o.weight
Skipping init for _hstu._attention_layers.1._o.bias
Skipping init for _hstu._attention_layers.2._uvqk
Skipping init for _hstu._attention_layers.2._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.2._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.2._o.weight
Skipping init for _hstu._attention_layers.2._o.bias
Skipping init for _hstu._attention_layers.3._uvqk
Skipping init for _hstu._attention_layers.3._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.3._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.3._o.weight
Skipping init for _hstu._attention_layers.3._o.bias
Skipping init for _hstu._attention_layers.4._uvqk
Skipping init for _hstu._attention_layers.4._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.4._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.4._o.weight
Skipping init for _hstu._attention_layers.4._o.bias
Skipping init for _hstu._attention_layers.5._uvqk
Skipping init for _hstu._attention_layers.5._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.5._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.5._o.weight
Skipping init for _hstu._attention_layers.5._o.bias
Skipping init for _hstu._attention_layers.6._uvqk
Skipping init for _hstu._attention_layers.6._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.6._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.6._o.weight
Skipping init for _hstu._attention_layers.6._o.bias
Skipping init for _hstu._attention_layers.7._uvqk
Skipping init for _hstu._attention_layers.7._rel_attn_bias._ts_w
Skipping init for _hstu._attention_layers.7._rel_attn_bias._pos_w
Skipping init for _hstu._attention_layers.7._o.weight
Skipping init for _hstu._attention_layers.7._o.bias
INFO:root:Restored model and optimizer state from epoch 75's ckpt: ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75. Setting cur_epoch to 75
" b'/rails/modeling/initialization.py:31: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  torch.nn.init.xavier_uniform(m.weight)
Traceback (most recent call last):
  File "/rails/eval_from_checkpoint.py", line 394, in <module>
    app.run(main)
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/rails/eval_from_checkpoint.py", line 387, in main
    mp.spawn(mp_train_fn,
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/rails/eval_from_checkpoint.py", line 373, in mp_train_fn
    train_fn(
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/rails/eval_from_checkpoint.py", line 307, in train_fn
    eval_dict = eval_metrics_v2_from_tensors(
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/rails/data/eval.py", line 284, in eval_metrics_v2_from_tensors
    eval_top_k_ids, eval_top_k_prs, _ = eval_state.candidate_index.get_top_k_outputs(
  File "/rails/indexing/candidate_index.py", line 179, in get_top_k_outputs
    top_k_prime_scores, top_k_prime_ids = top_k_module(query_embeddings=query_embeddings, k=k_prime, aux_payloads=aux_payloads)
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ashok-4983/miniconda3/envs/rails_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/rails/indexing/mol_top_k.py", line 251, in forward
    _, avg_sim_top_k_indices = torch.topk(avg_sim_values, k=self._avg_top_k, dim=1)
RuntimeError: selected index k out of range
  In call to configurable 'train_fn' (<function train_fn at 0x7f31886cb760>)

'
Traceback (most recent call last):
  File "/rails/eval_batch.py", line 95, in <module>
    result = eval(dataset=dataset, batch_size=batch_size)
  File "/rails/eval_batch.py", line 83, in eval
    eval_data.append(algorithm + "," + result[1])
TypeError: 'NoneType' object is not subscriptable
```

Any idea on how to resolve this?

**Comment by bailuding** [comment]
> ckpts/ml-1m-l200/HSTU-b8-h2-dqk25-dv25-lsilud0.2-ad0.0_MoL-8x4x64-t0.05-d0.2-l2-q512d0.0swiglu-id0.1-gq128-gi128d0.0-gqi128d0.0-x-glu_silu-uids6040d0.5_local_ssl-n128-b128-lr0.001-wu0-wd0.001-2024-06-19_ep75 --master_port=12346
> CUDA_VISIBLE_DEVICES=1 python3 eval_from_checkpoint.py --eva

The error indicates that K is too large for the dataset (ml-1m). This happens because the algorithm overfetches items for producing the final top K. Right now some of the configurations in your evaluation use large Ks, e.g., the top_k_method=MoLAvgTopK4000. Can you first try the configurations of small Ks and see if the code runs successfully?
